[[redirects]]
    from = "/using-typescript"
    to = "https://futuregerald-requestbin.herokuapp.com/1dl9irz1"
    status = 200

[[headers]]
    for = "/*"
    [headers.values]
    my-header: "netlify rocks"
